### PR TITLE
Add Asa Stats

### PR DESCRIPTION
**Pull request by ghost**
# Description

_Please include a summary of the resource you're suggesting below:_

# Checklist:

_Please make sure you reviewed the checklist and comply with each requirement:_

-   [x] My code follows the [contribution guidelines](../CONTRIBUTING.md) of this project
-   [x] This pull request has a title in the format `Add Name of Resource`:
    -   ✅ Add `py-algorand-sdk`
    -   ❌ Update readme.md

### CODE REVIEW

**Comment by aorumbayev** [comment]
@salvatorecorvaglia thanks for opening the PR!

Can you:
1. Fill PR description as the template says (just append the info on whats being added under description)
2. Fix styling in your proposal. The description for item should start with uppercase. 

Afterwards I can approve and merge this

**Review by aorumbayev — CHANGES_REQUESTED** [review]
see comment above

**Comment by salvatorecorvaglia** [comment]
Sorry, my mistake.

**Comment by aorumbayev** [comment]
@salvatorecorvaglia no worries, just an fyi for future PRs ;)

**Pull request closed without merging**
